package utils

import (
	"fmt"
	"testing"
)

func TestColorCli(_ *testing.T) {
	fmt.Println(Green("Green"))
	fmt.Println(LightGreen("LightGreen"))
	fmt.Println(Cyan("Cyan"))
	fmt.Println(LightCyan("LightCyan"))
	fmt.Println(Red("Red"))
	fmt.Println(LightRed("LightRed"))
	fmt.Println(Yellow("Yellow"))
	fmt.Println(Black("Black"))
	fmt.Println(DarkGray("DarkGray"))
	fmt.Println(LightGray("LightGray"))
	fmt.Println(White("White"))
	fmt.Println(Blue("Blue"))
	fmt.Println(LightBlue("LightBlue"))
	fmt.Println(Purple("Purple"))
	fmt.Println(LightPurple("LightPurple"))
	fmt.Println(Brown("Brown"))
	fmt.Println(Blue("Blue", 1, 1))

	fmt.Println(Green("Blink Green", 1, 1))
	fmt.Println(LightGreen("Blink LightGreen", 1))
	fmt.Println(Cyan("Blink Cyan", 1))
	fmt.Println(LightCyan("Blink LightCyan", 1))
	fmt.Println(Red("Blink Red", 1))
	fmt.Println(LightRed("Blink LightRed", 1))
	fmt.Println(Yellow("Blink Yellow", 1))
	fmt.Println(Black("Blink Black", 1))
	fmt.Println(DarkGray("Blink DarkGray", 1))
	fmt.Println(LightGray("Blink LightGray", 1))
	fmt.Println(White("Blink White", 1))
	fmt.Println(Blue("Blink Blue", 1))
	fmt.Println(LightBlue("Blink LightBlue", 1))
	fmt.Println(Purple("Blink Purple", 1))
	fmt.Println(LightPurple("Blink LightPurple", 1))
	fmt.Println(Brown("Blink Brown", 1))

	fmt.Println(Green("Blink & Underline Green", 1, 1, 1))
	fmt.Println(LightGreen("Blink & Underline LightGreen", 1, 1))
	fmt.Println(Cyan("Blink & Underline Cyan", 1, 1))
	fmt.Println(LightCyan("Blink & Underline LightCyan", 1, 1))
	fmt.Println(Red("Blink & Underline Red", 1, 1))
	fmt.Println(LightRed("Blink & Underline LightRed", 1, 1))
	fmt.Println(Yellow("Blink & Underline Yellow", 1, 1))
	fmt.Println(Black("Blink & Underline Black", 1, 1))
	fmt.Println(DarkGray("Blink & Underline DarkGray", 1, 1))
	fmt.Println(LightGray("Blink & Underline LightGray", 1, 1))
	fmt.Println(White("Blink & Underline White", 1, 1))
	fmt.Println(Blue("Blink & Underline Blue", 1, 1))
	fmt.Println(LightBlue("Blink & Underline LightBlue", 1, 1))
	fmt.Println(Purple("Blink & Underline Purple", 1, 1))
	fmt.Println(LightPurple("Blink & Underline LightPurple", 1, 1))
	fmt.Println(Brown("Blink & Underline Brown", 1, 1))
}
